In [55]:
import pandas as pd
import numpy as np
import seaborn as sns

In [56]:
num_rows = 10

# Generate 10 unique ages (or a range)
ages = np.arange(20, 30) # Example: 20, 21, ..., 29

# Possible values for categorical columns
genders = ['Male', 'Female', 'Non-binary']
reviews = ['Excellent', 'Average', 'Poor']
educations = ['High School', 'Bachelor', 'Master', 'PhD', 'Associate']
purchased_options = ['Yes', 'No']

# Generate random data for other columns ensuring 10 entries
gender_data = np.random.choice(genders, num_rows, replace=True)
review_data = np.random.choice(reviews, num_rows, replace=True)
education_data = np.random.choice(educations, num_rows, replace=True)
purchased_data = np.random.choice(purchased_options, num_rows, replace=True)

# Create the DataFrame
data = {
    'age': ages,
    'gender': gender_data,
    'review': review_data,
    'education': education_data,
    'purchased': purchased_data
}

df = pd.DataFrame(data)
print(df)

   age      gender     review    education purchased
0   20  Non-binary    Average       Master        No
1   21  Non-binary       Poor  High School       Yes
2   22      Female       Poor       Master       Yes
3   23      Female  Excellent    Associate       Yes
4   24  Non-binary  Excellent       Master        No
5   25        Male    Average  High School       Yes
6   26      Female    Average    Associate       Yes
7   27      Female    Average       Master       Yes
8   28      Female  Excellent    Associate        No
9   29      Female       Poor  High School       Yes

In [57]:
df.sample(5)

   age      gender     review    education purchased
3   23      Female  Excellent    Associate       Yes
2   22      Female       Poor       Master       Yes
9   29      Female       Poor  High School       Yes
5   25        Male    Average  High School       Yes
0   20  Non-binary    Average       Master        No

In [58]:
df = df[['review','education','purchased']]
df

      review    education purchased
0    Average       Master        No
1       Poor  High School       Yes
2       Poor       Master       Yes
3  Excellent    Associate       Yes
4  Excellent       Master        No
5    Average  High School       Yes
6    Average    Associate       Yes
7    Average       Master       Yes
8  Excellent    Associate        No
9       Poor  High School       Yes

In [59]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.2)

In [60]:
x_train

      review    education
0    Average       Master
7    Average       Master
1       Poor  High School
2       Poor       Master
6    Average    Associate
5    Average  High School
3  Excellent    Associate
8  Excellent    Associate

In [61]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Poor','Average','Excellent'],['High School','Bachelor','Master','PhD','Associate']])

In [62]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Excellent'],
                           ['High School', 'Bachelor', 'Master', 'PhD',
                            'Associate']])

In [63]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [64]:
x_train

array([[1., 2.],
       [1., 2.],
       [0., 0.],
       [0., 2.],
       [1., 4.],
       [1., 0.],
       [2., 4.],
       [2., 4.]])

In [65]:
oe.categories

[['Poor', 'Average', 'Excellent'],
 ['High School', 'Bachelor', 'Master', 'PhD', 'Associate']]

In [66]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(y_train)

LabelEncoder()

In [67]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [68]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [69]:
y_train,y_test

(array([0, 1, 1, 1, 1, 1, 1, 0]), array([0, 1]))

# One Hot Encoding

In [70]:
df = pd.read_csv("/content/car_price_prediction_.csv")

In [71]:
df.shape

(2500, 10)

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car ID        2500 non-null   int64
 1   Brand         2500 non-null   object
 2   Year          2500 non-null   int64
 3   Engine Size   2500 non-null   float64
 4   Fuel Type     2500 non-null   object
 5   Transmission  2500 non-null   object
 6   Mileage       2500 non-null   int64
 7   Condition     2500 non-null   object
 8   Price         2500 non-null   float64
 9   Model         2500 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 195.4+ KB

In [73]:
df.isnull().sum()

Car ID          0
Brand           0
Year            0
Engine Size     0
Fuel Type       0
Transmission    0
Mileage         0
Condition       0
Price           0
Model           0
dtype: int64

In [74]:
df.sample(5)

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
1878,1879,Mercedes,2003,4.1,Petrol,Manual,263552,New,82836.79,GLC
565,566,Ford,2007,2.8,Electric,Automatic,144854,Like New,86621.37,Mustang
492,493,Mercedes,2019,2.5,Petrol,Automatic,194941,Like New,56129.04,GLA
1110,1111,Ford,2015,2.6,Electric,Automatic,110573,New,31232.96,Mustang
10,11,Tesla,2001,1.8,Diesel,Automatic,298875,Like New,58872.60,Model 3

In [75]:
print(df['Fuel Type'].value_counts())
print(df['Transmission'].value_counts())

Fuel Type
Diesel      655
Petrol      630
Electric    614
Hybrid      601
Name: count, dtype: int64
Transmission
Manual       1308
Automatic    1192
Name: count, dtype: int64

##OneHotEncoding Using Pand

In [76]:
pd.get_dummies(df,columns=['Fuel Type','Transmission'],drop_first=True)

,Car ID,Brand,Year,Engine Size,Mileage,Condition,Price,Model,Fuel Type_Electric,Fuel Type_Hybrid,Fuel Type_Petrol,Transmission_Manual
0,1,Tesla,2016,2.3,114832,New,26613.92,Model X,False,False,True,True
1,2,BMW,2018,4.4,143190,Used,14679.61,5 Series,True,False,False,True
2,3,Audi,2013,4.5,181601,New,44402.61,A4,True,False,False,True
3,4,Tesla,2011,4.1,68682,New,86374.33,Model Y,False,False,False,False
4,5,Ford,2009,2.6,223009,Like New,73577.10,Mustang,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,Audi,2020,2.4,22650,Like New,61384.10,Q5,False,False,True,False
2496,2497,Audi,2001,5.7,77701,Like New,24710.35,A3,False,True,False,True
2497,2498,Ford,2021,1.1,272827,Like New,29902.45,Fiesta,False,True,False,True
2498,2499,Audi,2002,4.5,229164,Like New,46085.67,Q5,False,False,False,True
2499,2500,Toyota,2005,4.6,80978,Used,16594.14,RAV4,False,False,False,False

In [77]:
print("""
After applying One-Hot Encoding:

Fuel Type column is converted into:
- Fuel_Type_Electric
- Fuel_Type_Hybrid
- Fuel_Type_Petrol

Transmission column is converted into:
- Transmission_Manual (Automatic is dropped due to drop_first=True)

Each column now contains True/False (or 1/0),
which machine learning models can understand.
""")

After applying One-Hot Encoding:

Fuel Type column is converted into:
- Fuel_Type_Electric
- Fuel_Type_Hybrid
- Fuel_Type_Petrol

Transmission column is converted into:
- Transmission_Manual (Automatic is dropped due to drop_first=True)

Each column now contains True/False (or 1/0),
which machine learning models can understand.

In [78]:
# Convert boolean to integer (True=1, False=0)
df = df.astype({col: 'int' for col in df.select_dtypes(include='bool').columns})

df.head()

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,1,Tesla,2016,2.3,Petrol,Manual,114832,New,26613.92,Model X
1,2,BMW,2018,4.4,Electric,Manual,143190,Used,14679.61,5 Series
2,3,Audi,2013,4.5,Electric,Manual,181601,New,44402.61,A4
3,4,Tesla,2011,4.1,Diesel,Automatic,68682,New,86374.33,Model Y
4,5,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang

In [79]:
# Drop non-numeric columns (for ML preparation)
df_clean = df.drop(['Brand', 'Model'], axis=1)

df_clean.head()

,Car ID,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price
0,1,2016,2.3,Petrol,Manual,114832,New,26613.92
1,2,2018,4.4,Electric,Manual,143190,Used,14679.61
2,3,2013,4.5,Electric,Manual,181601,New,44402.61
3,4,2011,4.1,Diesel,Automatic,68682,New,86374.33
4,5,2009,2.6,Diesel,Manual,223009,Like New,73577.10

In [80]:
print("Final Dataset Info:\n")
df_clean.info()

Final Dataset Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car ID        2500 non-null   int64
 1   Year          2500 non-null   int64
 2   Engine Size   2500 non-null   float64
 3   Fuel Type     2500 non-null   object
 4   Transmission  2500 non-null   object
 5   Mileage       2500 non-null   int64
 6   Condition     2500 non-null   object
 7   Price         2500 non-null   float64
dtypes: float64(2), int64(3), object(3)
memory usage: 156.4+ KB

In [81]:
# Average price by condition
avg_price = df.groupby('Condition')['Price'].mean()

print("Average Price by Condition:\n", avg_price)

Average Price by Condition:
 Condition
Like New    53518.746376
New         51904.509951
Used        52470.919076
Name: Price, dtype: float64

In [82]:
# Select only numeric columns
df_numeric = df_clean.select_dtypes(include=['int64', 'float64'])

# Now apply correlation
corr = df_numeric.corr()

print(corr['Price'].sort_values(ascending=False))

Price          1.000000
Car ID         0.004650
Engine Size   -0.004420
Mileage       -0.008567
Year          -0.036805
Name: Price, dtype: float64

In [83]:
print("""
Conclusion:

1. Applied One-Hot Encoding on Fuel Type and Transmission
2. Converted boolean values into numeric format
3. Removed unnecessary text columns
4. Prepared dataset for Machine Learning
5. Performed basic analysis on Price

Now the dataset is ready for model training.
""")

Conclusion:

1. Applied One-Hot Encoding on Fuel Type and Transmission
2. Converted boolean values into numeric format
3. Removed unnecessary text columns
4. Prepared dataset for Machine Learning
5. Performed basic analysis on Price

Now the dataset is ready for model training.