# Mice - Multivariate Imputation by Chained

In [20]:
import numpy as np
import pandas as pd

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

In [22]:
df = pd.read_csv('/content/train.csv',usecols = ['Age','Fare','Survived'])

In [23]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [24]:
df.isnull().mean() *100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [25]:
x = df.drop(columns = ['Survived'])
y = df['Survived']

In [26]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 2)

In [27]:
x_train.head()

      Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

In [31]:
ii = IterativeImputer()
x_train_trf = ii.fit_transform(x_train)
x_test_trf = ii.fit_transform(x_test)

In [34]:
lr = LogisticRegression()

lr.fit(x_train_trf,y_train)

y_pred = lr.predict(x_test_trf)

accuracy_score(y_test,y_pred)

0.6145251396648045

In [38]:
si = SimpleImputer(strategy='median')

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.fit_transform(x_test)

In [39]:
lr = LogisticRegression()

lr.fit(x_train_trf2,y_train)

y_pred2 = lr.predict(x_test_trf2)

accuracy_score(y_test,y_pred2)

0.6145251396648045